# Don't override the 'source' setting!
# https://jekyllrb.com/docs/github-pages/#project-pages
# https://help.github.com/articles/generic-jekyll-build-failures/#source-setting

# Site settings
title: Sean Fisk
email: sean@seanfisk.com
description: Personal blog of Sean Fisk
url: "http://seanfisk.com" # the base hostname & protocol for your site
github_username: seanfisk

# Build settings
markdown: kramdown

permalink: /:year/:month/:title
